# Generated by Django 5.0.1 on 2024-01-28 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_post_post_user_postcomment_postreact_postview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_share', to='posts.post'),
        ),
    ]
